// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtr4YxUIDzMARKWHJUjtKYJoCo3RUQQmw',
    appId: '1:30736213150:web:c403e4588e93347ca0078f',
    messagingSenderId: '30736213150',
    projectId: 'cleanup-44c1b',
    authDomain: 'cleanup-44c1b.firebaseapp.com',
    storageBucket: 'cleanup-44c1b.appspot.com',
    measurementId: 'G-GEP4B7C2PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs3LWU8ibikwA_Leh-gvw2XOD7OBY_Rck',
    appId: '1:30736213150:android:64ca324d5dea35c1a0078f',
    messagingSenderId: '30736213150',
    projectId: 'cleanup-44c1b',
    storageBucket: 'cleanup-44c1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvopU4Im9TDlE5k0wQF3MDvshLcADJxCY',
    appId: '1:30736213150:ios:3a45b5e58dd72000a0078f',
    messagingSenderId: '30736213150',
    projectId: 'cleanup-44c1b',
    storageBucket: 'cleanup-44c1b.appspot.com',
    androidClientId: '30736213150-3vma3o1fatv189f56kvdmrm3l7uoaghr.apps.googleusercontent.com',
    iosClientId: '30736213150-0q7nt5lcaej89mr7ue81lfqkns2pikdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanupMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvopU4Im9TDlE5k0wQF3MDvshLcADJxCY',
    appId: '1:30736213150:ios:3a45b5e58dd72000a0078f',
    messagingSenderId: '30736213150',
    projectId: 'cleanup-44c1b',
    storageBucket: 'cleanup-44c1b.appspot.com',
    androidClientId: '30736213150-3vma3o1fatv189f56kvdmrm3l7uoaghr.apps.googleusercontent.com',
    iosClientId: '30736213150-0q7nt5lcaej89mr7ue81lfqkns2pikdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cleanupMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtr4YxUIDzMARKWHJUjtKYJoCo3RUQQmw',
    appId: '1:30736213150:web:6a1b6def1b25437ca0078f',
    messagingSenderId: '30736213150',
    projectId: 'cleanup-44c1b',
    authDomain: 'cleanup-44c1b.firebaseapp.com',
    storageBucket: 'cleanup-44c1b.appspot.com',
    measurementId: 'G-LS13RHJREZ',
  );
}
